### ISSUE TITLE
Need tiny rec files for testing

### ISSUE THREAD

**Issue by edeno** [LorenFrankLab/spikegadgets_to_nwb#1]
Need several to mimic epochs.

**Comment by edeno** [comment]
Possible candidates:
`/cumulus/xulu/Isaac/20230609/20230609_Isaac_02_r2/20230609_Isaac_02_r2.rec`: 1.4 GB
`/cumulus/xulu/Isaac/20230609/20230609_Isaac_11_r7/20230609_Isaac_11_r7.rec` : ~600 MB

**Comment by edeno** [comment]
Other candidates:
+ `/stelmo/kyu/L5/kyu10s/20230622_155936`
+ `/stelmo/kyu/L5/kyu10s/20230622_160016`

**Comment by rly** [comment]
Great, thanks! I uploaded Kyu's example recordings to https://ucsf.box.com/s/8ygc60e67e2z1p9qw7jkvnfjf26cztel and gave @edeno and @samuelbray32 co-ownership over the Box folder.

**Comment by rly** [comment]
We can set up CI to download the data from there.
