### ISSUE TITLE
Timestamps for video_files

### ISSUE THREAD

**Issue by samuelbray32** [LorenFrankLab/spikegadgets_to_nwb#31]
In add_associated_video_files, we need to take the timestamps (ptp enabled or non-enabled) and include it in the image-series object created. If this information is already being found when adding position maybe we can call the function from there, or call add_associated_video_files after position has been added and find the timestamps in the nwbfile?

**Comment by edeno** [comment]
Yeah, it should come from the code handling the position timestamps.

**Comment by samuelbray32** [comment]
Addressed in 9a2186747ae53d5def0a430937f9a78a098805fe
