### ISSUE TITLE
Multiple Behavior Event objects for the same Dio pin

### ISSUE THREAD

**Issue by samuelbray32** [LorenFrankLab/spikegadgets_to_nwb#44]
Should the User be allowed to create multiple behavioral event objects from the same DIO data? This is allowed in rec_to_nwb, but seems a redundant waste of memory.

**Comment by lfrank** [comment]
I don’t think this is necessary or helpful, so let’s go with no unless someone has a strong objection.


On Sep 20, 2023, at 1:19 PM, Samuel Bray ***@***.***> wrote:

﻿
Should the User be allowed to create multiple behavioral event objects from the same DIO data? This is allowed in rec_to_nwb, but seems a redundant waste of memory. — Reply to this email directly, view it on GitHub, or unsubscribe. You
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

Should the User be allowed to create multiple behavioral event objects from the same DIO data? This is allowed in rec_to_nwb, but seems a redundant waste of memory.

**Comment by edeno** [comment]
Agree, I have not heard of a case where someone is using this.
