### ISSUE TITLE
Include probe metadata in package

### ISSUE THREAD

**Issue by samuelbray32** [LorenFrankLab/spikegadgets_to_nwb#45]
Since some probe metadata files are commonly used by lab members, should we include some of them by default in the package.  People can still reference paths to new metadata files, but it should save people steps in most cases

**Comment by edeno** [comment]
I'm a fan of decreasing the amount of work people do.

**Comment by rly** [comment]
I agree

**Comment by samuelbray32** [comment]
https://github.com/LorenFrankLab/spikegadgets_to_nwb/commit/450df60873b1db172c20c87feeb5c06c04034fb5
