### ISSUE TITLE
Wrapping of trodes timestamps in large dataset

### ISSUE THREAD

**Issue by samuelbray32** [LorenFrankLab/spikegadgets_to_nwb#59]
During a large, continuous recording dataset observed the trodes timestamps wrap from the max uint32 value of 4294967295.  This causes issues in non-ptp `add_position` when using digitize since the sample count is now non-monotonic.  

Fully resolving this in `SpikegadgetsRawIO` would require unwrapping and changing to something other than a `unint32` .  

Alternatively could use something other than `digitize()` to locate indices if we accept looping of timestamps in the final nwb

**Comment by edeno** [comment]
I think converting the dtype and unwrapping makes the most sense. Maybe only do this in the case where we are getting close to this value?

**Comment by samuelbray32** [comment]
I talked to Loren, and saving the unwrapped value in the nwb could create errors when comparing to other saved files that use the trodes timestamp.  We can instead just resolve the error that arises from `digitize` in the non-ptp case and leave the rest as-is.

**Comment by edeno** [comment]
Fixed by #61
